<?xml version="1.0"?>
<package format="3">
  <name>autodrive_f1tenth</name>
  <version>0.1.0</version>
  <description>In-repo ROS2 package for simulator-side F1TENTH controllers.</description>
  <maintainer email="malik@example.com">malik</maintainer>
  <license>BSD-3-Clause</license>

  <buildtool_depend>ament_python</buildtool_depend>

  <depend>geometry_msgs</depend>
  <depend>launch</depend>
  <depend>launch_ros</depend>
  <depend>nav_msgs</depend>
  <depend>rclpy</depend>
  <depend>sensor_msgs</depend>
  <depend>std_msgs</depend>
  <depend>tf2_ros</depend>
  <depend>visualization_msgs</depend>
  <exec_depend>slam_toolbox</exec_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
